# Generated by Django 2.1.2 on 2018-10-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0002_auto_20181015_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('excelTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec.ExcelTable')),
            ],
        ),
    ]
