# Generated by Django 2.1.2 on 2018-10-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_tabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltable',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
